### ISSUE TITLE
Consider making cargo command that will assist in the docker workflow

### ISSUE THREAD

**Issue by frewsxcv** [rust-fuzz/afl.rs#110]
Simplify some of the process described in http://blog.troutwine.us/2017/01/06/american-fuzzy-loping-rust/

Ideally, the user should never have to directly run `docker` themselves. It could also set up a Docker volume which maps to somewhere in the host filesystem acting as a cargo cache so we didn't have to fetch dependencies each time we run start a docker container and do `cargo build`.

**Comment by blt** [comment]
Relevant to my interests. Happy to test in-progress work and will write an update to that post when the command is available.

**Comment by frewsxcv** [comment]
just published afl.rs 0.2. docker flow is no longer necessary 🎊 

https://twitter.com/frewsxcv/status/932799107487461377

https://users.rust-lang.org/t/announcing-afl-rs-0-2-bindings-for-american-fuzzy-lop/13981
