### ISSUE TITLE
Update rust toolchain in docker image

### ISSUE THREAD

**Issue by daschl** [rust-fuzz/afl.rs#111]
Hi,

I've been trying to fuzz a library which has a dependency on a git repository with workspaces. This is not supported with 1.11 that is currently used in the image. It fails with:

```
  no `package` or `project` section found.
```

I think this has been fixed in later cargo versions (https://github.com/rust-lang/cargo/pull/2938), would it be possible to upgrade the docker image with a newer rust toolchain?

Thanks!

**Comment by daschl** [comment]
Note that I think I could work around it by manually updating it to `curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly --disable-sudo`.

**Comment by frewsxcv** [comment]
just rewrote afl.rs, it's no longer docker based. see [this URLO post for more info](https://users.rust-lang.org/t/announcing-afl-rs-0-2-bindings-for-american-fuzzy-lop/13981).
