### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by frewsxcv** [rust-fuzz/afl.rs#118]
Blocked on https://github.com/rust-lang/rust/issues/22915

**Comment by frewsxcv** [comment]
https://github.com/rust-lang/rust/issues/22915 is now resolved, afl.rs works on mac now! 🎊

**Comment by rubberduck203** [comment]
For anyone running across this issue, as of 3/17/18 you have to use the nightly build to get passed the following error.

```
LLVM ERROR: Global variable '__sancov_gen_' has an invalid section specifier '__sancov_guards': mach-o section specifier requires a segment and section separated by a comma.
```
