### ISSUE TITLE
Use default values for command line arguments

### ISSUE THREAD

**Issue by coder543** [rust-fuzz/afl.rs#127]
In [the tutorial](https://rust-fuzz.github.io/book/afl/tutorial.html), it shows that you should use this command:

    cargo afl fuzz -i in -o out target/debug/url-fuzz-target

I don't think many people would change the `in` or `out` directories, so it seems like those should only need to be provided in the rare case that someone does.

The target executable could also be inferred for most cases, I would imagine.

Ideally, the user could just run `cargo afl fuzz` and get sane results.

**Comment by frewsxcv** [comment]
Thanks for opening this issue! While I appreciate sharing the idea and can understand where you're coming from, I'm interested in keeping the command line args/behavior identical to the `afl-fuzz` command. Thanks again for the idea though! 🙇
