### ISSUE TITLE
serde_derive dependencies break afl build

### ISSUE THREAD

**Issue by dhuseby** [rust-fuzz/afl.rs#128]
Whenever I try to fuzz a library that has serde_derive as a dependency, I get this error message:

`error: the linked panic runtime 'panic_unwind' is not compiled with this crate's panic strategy 'abort'`

I think I grok what the error means but I'm not sure the exact solution.  I thought I post this here to see if anybody else is running into this and has found a solution.

**Comment by frewsxcv** [comment]
This should be fixed with https://github.com/rust-fuzz/afl.rs/pull/123, so you should just need to bump afl.rs in your Cargo.roml and `cargo install --force afl`. Reopen if you still have any issues
