### ISSUE TITLE
separate binary and lib or their deps

### ISSUE THREAD

**Issue by Trolldemorted** [rust-fuzz/afl.rs#130]
Right now it is cumbersome to fuzz libs that depend on afl.rs' dependencies, because they may require different versions.

Since the lib only offers two functions and uses nothing of the dependencies (?), I think we don't need them to be included in fuzz targets.

**Comment by frewsxcv** [comment]
which dependencies are you referring to? some of them get used in the [`cargo-afl`](https://github.com/rust-fuzz/afl.rs/blob/master/src/bin/cargo-afl.rs) binary. in what ways do you find working with the dependencies cumbersome?

**Comment by Trolldemorted** [comment]
We are fuzzing something also depending on clap, but a completely different version.

Since the fuzz target does not need clap we cloned afl.rs, removed everything cargo-afl related, built our fuzz-target, and ran it with cargo afl from crates.io.

**Comment by frewsxcv** [comment]
Relevant cargo issue https://github.com/rust-lang/cargo/issues/1982

**Comment by frewsxcv** [comment]
For what it's worth, you don't need to add 'afl' as a dependency in your cargo.toml. you should be able to just copy and paste [these functions](https://github.com/rust-fuzz/afl.rs/blob/master/src/lib.rs) into your fuzz target

**Comment by Trolldemorted** [comment]
depending on a local, purged clone of afl.rs also works like a charm, we just wanted to let you know

**Comment by smoelius** [comment]
I think issue #335 was a duplicate of this one, and that issue is now closed.

Feel free to reopen if I have made a mistake.
