### ISSUE TITLE
Add support for AFL Persistent Mode

### ISSUE THREAD

**Issue by domenukk** [rust-fuzz/afl.rs#131]
Great Project!
One problem I have is that startup for my binary is pretty slow.
The way I understood it, afl is given the actual binary to execute and will fork on _start.
Since the afl.rs api already wraps every call in a closure, it would map perfectly to Persistent Mode:
https://github.com/mirrorer/afl/blob/master/llvm_mode/README.llvm#L139
That way execution speed (at least the setup) should be a lot quicker.
A good middle ground might be the start the delayed fork server at the rust afl entrypoint.

**Comment by PaulGrandperrin** [comment]
Maybe you should try [cargo-fuzz](https://github.com/rust-fuzz/cargo-fuzz) or [honggfuzz-rs](https://github.com/rust-fuzz/honggfuzz-rs).

Disclaimer: I'm the author of honggfuzz-rs.

**Comment by PaulGrandperrin** [comment]
Also I want to point out that I'm working on making this happen in AFL.rs.
I have a working version but the speedup is not that great...
For instance fuzzing `url` on my computer, using 1 thread:
AFL.rs **w/o** persistent mode: ~2000/s
AFL.rs **w/** persistent mode: ~10000/s
Honggfuzz **w/** persistent mode: ~ 60000/s

**Comment by frewsxcv** [comment]
Done in https://github.com/rust-fuzz/afl.rs/pull/137
