### ISSUE TITLE
Yank afl-sys and afl-plugin

### ISSUE THREAD

**Issue by PaulGrandperrin** [rust-fuzz/afl.rs#136]
`afl-sys` and `afl-plugin` are still available on crates.io and are cumulating roughly 400 recent downloads.

I don't really know what are the recommendations (if there are any) about deprecating crates but maybe [yanking](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-yank) them all is something to do.

Another (complementary) solution might be to release a new minor version `0.1.6` with a depreciation warning.

**Comment by frewsxcv** [comment]
just yanked them all 🙈
