### ISSUE TITLE
Build fails while installing afl 0.4.0 using cargo install

### ISSUE THREAD

**Issue by Shadlock0133** [rust-fuzz/afl.rs#140]
Tried updating from version 0.3.2 to 0.4.0.

<details><summary>Log</summary>
<p>
<pre><font color="#DC9656"><b>➜  </b></font><font color="#A16946"><b>~</b></font> cargo install --force afl
<font color="#282828"><b>    Updating</b></font> registry `https://github.com/rust-lang/crates.io-index`
<font color="#282828"><b>  Installing</b></font> afl v0.4.0                                                         
<font color="#282828"><b>   Compiling</b></font> semver-parser v0.7.0
<font color="#282828"><b>   Compiling</b></font> xdg v2.1.0
<font color="#282828"><b>   Compiling</b></font> unicode-width v0.1.5
<font color="#282828"><b>   Compiling</b></font> libc v0.2.42
<font color="#282828"><b>   Compiling</b></font> bitflags v1.0.3
<font color="#282828"><b>   Compiling</b></font> strsim v0.7.0
<font color="#282828"><b>   Compiling</b></font> ansi_term v0.11.0
<font color="#282828"><b>   Compiling</b></font> vec_map v0.8.1
<font color="#282828"><b>   Compiling</b></font> cc v1.0.18
<font color="#282828"><b>   Compiling</b></font> semver v0.9.0
<font color="#282828"><b>   Compiling</b></font> textwrap v0.10.0
<font color="#282828"><b>   Compiling</b></font> atty v0.2.10
<font color="#282828"><b>   Compiling</b></font> rustc_version v0.2.2
<font color="#282828"><b>   Compiling</b></font> clap v2.32.0
<font color="#282828"><b>   Compiling</b></font> afl v0.4.0
<font color="#DC9656"><b>error:</b></font> failed to run custom build command for `afl v0.4.0`
process didn&apos;t exit successfully: `/tmp/cargo-installhMIfsD/release/build/afl-510925da3c09f455/build-script-build` (exit code: 101)
--- stdout
rm -f afl-gcc afl-fuzz afl-showmap afl-tmin afl-gotcpu afl-analyze afl-as as afl-g++ afl-clang afl-clang++ *.o *~ a.out core core.[1-9][0-9]* *.stackdump test .test test-instr .test-instr0 .test-instr1 qemu_mode/qemu-2.10.0.tar.bz2 afl-qemu-trace
rm -rf out_dir qemu_mode/qemu-2.10.0
make -C llvm_mode clean
make[1]: Entering directory &apos;/home/shadlock0133/.cargo/registry/src/github.com-1ecc6299db9ec823/afl-0.4.0/afl-2.52b/llvm_mode&apos;
rm -f *.o *.so *~ a.out core core.[1-9][0-9]* test-instr .test-instr0 .test-instr1 
rm -f ../afl-clang-fast ../afl-llvm-rt.o ../afl-llvm-rt-32.o ../afl-llvm-rt-64.o ../afl-clang-fast++
make[1]: Leaving directory &apos;/home/shadlock0133/.cargo/registry/src/github.com-1ecc6299db9ec823/afl-0.4.0/afl-2.52b/llvm_mode&apos;
make -C libdislocator clean
make[1]: Entering directory &apos;/home/shadlock0133/.cargo/registry/src/github.com-1ecc6299db9ec823/afl-0.4.0/afl-2.52b/libdislocator&apos;
rm -f *.o *.so *~ a.out core core.[1-9][0-9]*
rm -f libdislocator.so
make[1]: Leaving directory &apos;/home/shadlock0133/.cargo/registry/src/github.com-1ecc6299db9ec823/afl-0.4.0/afl-2.52b/libdislocator&apos;
make -C libtokencap clean
make[1]: Entering directory &apos;/home/shadlock0133/.cargo/registry/src/github.com-1ecc6299db9ec823/afl-0.4.0/afl-2.52b/libtokencap&apos;
rm -f *.o *.so *~ a.out core core.[1-9][0-9]*
rm -f libtokencap.so
make[1]: Leaving directory &apos;/home/shadlock0133/.cargo/registry/src/github.com-1ecc6299db9ec823/afl-0.4.0/afl-2.52b/libtokencap&apos;
[*] Checking for the ability to compile x86 code...
[+] Everything seems to be working, ready to compile.
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\&quot;/lib/afl\&quot; -DDOC_PATH=\&quot;/share/doc/afl\&quot; -DBIN_PATH=\&quot;/bin\&quot; afl-gcc.c -o afl-gcc -ldl
set -e; for i in afl-g++ afl-clang afl-clang++; do ln -sf afl-gcc $i; done
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\&quot;/lib/afl\&quot; -DDOC_PATH=\&quot;/share/doc/afl\&quot; -DBIN_PATH=\&quot;/bin\&quot; afl-fuzz.c -o afl-fuzz -ldl
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\&quot;/lib/afl\&quot; -DDOC_PATH=\&quot;/share/doc/afl\&quot; -DBIN_PATH=\&quot;/bin\&quot; afl-showmap.c -o afl-showmap -ldl
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\&quot;/lib/afl\&quot; -DDOC_PATH=\&quot;/share/doc/afl\&quot; -DBIN_PATH=\&quot;/bin\&quot; afl-tmin.c -o afl-tmin -ldl
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\&quot;/lib/afl\&quot; -DDOC_PATH=\&quot;/share/doc/afl\&quot; -DBIN_PATH=\&quot;/bin\&quot; afl-gotcpu.c -o afl-gotcpu -ldl
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\&quot;/lib/afl\&quot; -DDOC_PATH=\&quot;/share/doc/afl\&quot; -DBIN_PATH=\&quot;/bin\&quot; afl-analyze.c -o afl-analyze -ldl
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\&quot;/lib/afl\&quot; -DDOC_PATH=\&quot;/share/doc/afl\&quot; -DBIN_PATH=\&quot;/bin\&quot; afl-as.c -o afl-as -ldl
ln -sf afl-as as
[*] Testing the CC wrapper and instrumentation output...
unset AFL_USE_ASAN AFL_USE_MSAN; AFL_QUIET=1 AFL_INST_RATIO=100 AFL_PATH=. ./afl-gcc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\&quot;/lib/afl\&quot; -DDOC_PATH=\&quot;/share/doc/afl\&quot; -DBIN_PATH=\&quot;/bin\&quot; test-instr.c -o test-instr -ldl
echo 0 | ./afl-showmap -m none -q -o .test-instr0 ./test-instr
echo 1 | ./afl-showmap -m none -q -o .test-instr1 ./test-instr

Oops, the instrumentation does not seem to be behaving correctly!

Please ping &lt;lcamtuf@google.com&gt; to troubleshoot the issue.

Makefile:90: recipe for target &apos;test_build&apos; failed

--- stderr
make: *** [test_build] Error 1
thread &apos;main&apos; panicked at &apos;assertion failed: status.success()&apos;, build.rs:29:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

<font color="#383838"><b>warning:</b></font> build failed, waiting for other jobs to finish...
<font color="#DC9656"><b>error:</b></font> failed to compile `afl v0.4.0`, intermediate artifacts can be found at `/tmp/cargo-installhMIfsD`

Caused by:
  build failed
</pre>
</p>
</details>

**Comment by dirvine** [comment]
Confirm, same with myself.

**Comment by thelearnerofcode** [comment]
The problem seems to be in upstream AFL, I get the same error when compiling from their source.

The solution is to change this line in the Makefile::
`@cmp -s .test-instr0 .test-instr1; DR="$$?"; rm -f .test-instr0 .test-instr1; if [ "$$DR" = "0" ]; then echo; echo "Oops, the instrumentation does not seem to be behaving correctly!"; echo; echo "Please ping <lcamtuf@google.com> to troubleshoot the issue."; echo; exit 1; fi`

to this:

`@cmp -s .test-instr0 .test-instr1; DR="$?"; rm -f .test-instr0 .test-instr1; if [ "$$DR" = "0" ]; then echo; echo "Oops, the instrumentation does not seem to be behaving correctly!"; echo; echo "Please ping <lcamtuf@google.com> to troubleshoot the issue."; echo; exit 1; fi`

**Comment by frewsxcv** [comment]
Since this is a bug with upstream AFL, I don't think there's anything actionable I can do here, so I'm going to close this

**Comment by KodrAus** [comment]
Does anyone know if this issue's been raised upstream on AFL's mailing list?
