### ISSUE TITLE
Linking error on OSX and afl.rs 0.4.2

### ISSUE THREAD

**Issue by gnieto** [rust-fuzz/afl.rs#146]
I was adding AFL on a project and I think that 0.4.2 release of AFL.rs broke support for OSX. See: https://github.com/sunchao/parquet-rs/pull/190#issuecomment-438956043

I think that it's related to https://github.com/rust-fuzz/afl.rs/pull/144/files, which force the linkage with gold and is not available on OSX machines.

It seems that AFL 0.4.1 is working properly on OSX. Maybe the work arround on #144 should be conditionally compiled only on Linux?

**Comment by breeswish** [comment]
I met the same issue.

**Comment by frewsxcv** [comment]
Opened a PR for this locally: https://github.com/rust-fuzz/afl.rs/pull/147

Confirmed that it afl.rs works again on macOS after that PR. I'll merge shortly. Thanks for being patient!
