### ISSUE TITLE
Open to "resettable" lazy_static PR?

### ISSUE THREAD

**Issue by smoelius** [rust-fuzz/afl.rs#164]
`lazy_static` variables present a problem when fuzzing with AFL in persistent mode (the default for afl.rs).  This fact was observed by @pedrocr in #152:
> Apparently lazy_static is something that needs to be handled carefully for afl. It ends up only being initialized inside the loop instead of only once. It's easy to work around in this codebase but it may be something that needs to be fixed more fully for other codebases to work well.

To address this problem, I wrote a ["resettable" version of `lazy_static`](https://github.com/smoelius/resettable-lazy-static.rs). Intuitively, the resettable version collects all initialized `lazy_static` variables in a linked list.  A call to `lazy_static::lazy::reset()` walks the linked list and uninitializes each variable.

An example of its use can be found [here](https://github.com/smoelius/fuzz-lazy-static).

The `lazy_static` maintainers [did not want to merge this](https://github.com/rust-lang-nursery/lazy-static.rs/pull/164#issuecomment-569457960), as it complicates the `get` operation. (Their position is understandable.)

So, would you be open to a PR that does the following?
* Adds a call to `lazy_static::lazy::reset()` between [these two lines](https://github.com/rust-fuzz/afl.rs/blob/503c1943c4f9a5b927da5cb5094553570a8b0bd1/src/lib.rs#L173-L174), guarded by a `reset-lazy-static` feature.
* Adds a section to the README explaining how one can use cargo's [patching mechanism](https://doc.rust-lang.org/edition-guide/rust-2018/cargo-and-crates-io/replacing-dependencies-with-patch.html) to substitute the resettable version of `lazy_static` for the standard one.

I regard to the second bullet, I think it would be better if the README referred readers to a rust-fuzz repository.  So, I would offer to let rust-fuzz hold the "official" resettable `lazy_static`.  Please let me know if this is something that you would like to do.

**Comment by frewsxcv** [comment]
hey @smoelius, i don't have much time nowadays to maintain afl.rs. your proposed change sounds good to me! i just sent you an invite to the rust-fuzz organization if you're interested in making any changes to afl.rs

**Comment by smoelius** [comment]
Great and thanks! I will submit the changes soon.
