### ISSUE TITLE
Consider switching to aflplusplus

### ISSUE THREAD

**Issue by Shnatsel** [rust-fuzz/afl.rs#167]
The original AFL has not been updated since 2017.

https://github.com/vanhauser-thc/AFLplusplus is an AFL fork with community patches and [demonstrates better results than AFL](https://www.fuzzbench.com/reports/sample/index.html) on Google's new [FuzzBench](https://security.googleblog.com/2020/03/fuzzbench-fuzzer-benchmarking-as-service.html).

**Comment by frewsxcv** [comment]
switched in https://github.com/rust-fuzz/afl.rs/pull/169
