### ISSUE TITLE
upgrade afl to 2.56b

### ISSUE THREAD

**Issue by SSebo** [rust-fuzz/afl.rs#168]
hi, tikv used this great crate, but I can not compile because AFL source code can not. I found recently it is fixed. 
Could you upgrade to the 2.56b?  Can I  make a PR ? I found `afl-*` is ignored in `.gitignore`.

**Comment by frewsxcv** [comment]
When you say 2.56b, are you referring to aflplusplus? https://github.com/rust-fuzz/afl.rs/issues/167
