### ISSUE TITLE
Unknown pass name 'sancov'

### ISSUE THREAD

**Issue by smoelius** [rust-fuzz/afl.rs#192]
https://github.com/rust-fuzz/cargo-fuzz/issues/276

`afl.rs` suffers from this issue as well: 
https://github.com/rust-fuzz/afl.rs/blob/29134042d23f198ccf4f8fa77eb68e398eb56cff/src/bin/cargo-afl.rs#L307
https://github.com/rust-fuzz/afl.rs/blob/29134042d23f198ccf4f8fa77eb68e398eb56cff/src/bin/cargo-afl.rs#L326

There seem to be at least two options:
* Wait and see what `cargo-fuzz` does.
* Charge ahead and implement a fix for the latest nightly.

I don't have a strong opinion. Does anyone else?

**Comment by smoelius** [comment]
`cargo-fuzz` has published a fix: https://github.com/rust-fuzz/cargo-fuzz/pull/277

**Comment by charlesxsh** [comment]
This error is caused by new LLVM pass manager, which sancov has a new name called "sancov-module". The fix should check llvm version to decide which name should be used.

**Comment by charlesxsh** [comment]
The workaround could be passing -Znew-llvm-pass-manager=no to avoid new LLVM pass manager.
If running in Cargo, it will be `RUSTFLAGS="-Znew-llvm-pass-manager=no " cargo ...`

**Comment by smoelius** [comment]
> @smoelius The workaround could be passing -Znew-llvm-pass-manager=no to avoid new LLVM pass manager. If running in Cargo, it will be `RUSTFLAGS="-Znew-llvm-pass-manager=no" cargo ...`

@charlesxsh I'm sorry for having gotten sidetracked with #193. But your suggestion was very helpful, and I did actually make use it. Thank you very much.

**Comment by smoelius** [comment]
https://github.com/rust-lang/rust/commit/150bd8ba76722a46fd8a7aacb81c7072a8b677dc
