### ISSUE TITLE
Incompatible with Arbitrary crate

### ISSUE THREAD

**Issue by ParkMyCar** [rust-fuzz/afl.rs#209]
I'm tried to use `afl 0.12` with `arbitrary 1.0`, but it looks like [the code generated by the `fuzz!` macro](https://github.com/rust-fuzz/afl.rs/blob/master/src/lib.rs#L161) depends on `arbitrary::RingBuffer` which looks like it was removed back in [`arbitrary 0.3`](https://github.com/rust-fuzz/arbitrary/blob/master/CHANGELOG.md#030). I believe the code that references `arbitrary::RingBuffer` needs to be updated to use `arbitrary::Unstructured`

**Comment by smoelius** [comment]
Thanks for the report, @ParkMyCar. It looks like we're not testing currently testing this feature, though we probably should.

Would you like to submit a PR? If not, I can try to get to this within the next week or so.

**Comment by ParkMyCar** [comment]
Hey @smoelius, thanks for taking a look so quick! I just put up a PR which should fix the issue, and adds an example, which I think should get built as part of CI
