### ISSUE TITLE
[Bug] afl.rs>=0.12.9 passes own arguments to `afl-fuzz`

### ISSUE THREAD

**Issue by roypat** [rust-fuzz/afl.rs#273]
Starting in version `0.12.9` (coinciding with the upgrade to `clap v4.0`), arguments passed to `cargo afl fuzz` are passed down to `afl++`, where they cause errors as they cannot be parsed. This makes the `max_total_time` option unusable, as it leads to:

```bash
[...]/afl.rs/rustc-1.64.0-a55dd71/afl.rs-0.12.9/afl/bin/afl-fuzz: invalid option -- '-'

[-] PROGRAM ABORT : Bad syntax used for -m
         Location : main(), src/afl-fuzz.c:860

```

whereas on `0.12.8` everything works as expected

**Comment by smoelius** [comment]
Thank you very much for the bug report. I will get to work on a fix.

But may I please ask, does `-V seconds` meet your needs?

`max_total_time` is a bit of an oddball and hence a maintenance burden. If the same functionality can be achieved with `-V`, then I would like to consider deprecating `max_total_time`.

**Comment by roypat** [comment]
Thank you so much for getting back to me so quickly! Yes, passing `-V seconds` instead met my needs!
