### ISSUE TITLE
Add optional feature to not set 'fuzzing' flag

### ISSUE THREAD

**Issue by lrubasze** [rust-fuzz/afl.rs#305]
Some crates (eg. `secp256k1`) stub some functions, when they detect 'fuzzing' flag, which makes them useless when fuzzing.

Idea is to add optional feature, that will prevent from setting `fuzzing` flag.

**Comment by smoelius** [comment]
Hey, @lrubasze. Okay if we close this?

**Comment by lrubasze** [comment]
Hi @smoelius. Of course :)
