### ISSUE TITLE
Multi Threaded Support

### ISSUE THREAD

**Issue by wcampbell0x2a** [rust-fuzz/afl.rs#313]
Could `afl-rs` support any parallel fuzzing such as the following document describes?

https://github.com/mirrorer/afl/blob/master/docs/parallel_fuzzing.txt

**Comment by smoelius** [comment]
Hi, @wcampbell0x2a. This should work today, though the commands needed are slightly different than what that document gives. Instead of:
```
./afl-fuzz -i testcase_dir -o sync_dir -M fuzzer01 [...other stuff...]

./afl-fuzz -i testcase_dir -o sync_dir -S fuzzer02 [...other stuff...]
```
One would write:
```
cargo afl fuzz -i testcase_dir -o sync_dir -M fuzzer01 [...other stuff...]

cargo afl fuzz -i testcase_dir -o sync_dir -S fuzzer02 [...other stuff...]
```
Please let me know if I've missed something.

**Comment by wcampbell0x2a** [comment]
Thanks!
