### ISSUE TITLE
More effective fuzzing

### ISSUE THREAD

**Issue by vanhauser-thc** [rust-fuzz/afl.rs#323]
I got a question concerning this afl.rs implementation and reviewed the setup.

What I gathered is that basically afl-fuzz is compiled, but none of the llvm plugins, and instead the vanilla llvm features are used (specifically sancov).
This makes the integration easy, on the other hand cool features are then not available in the project, namely cmplog, auto dictionary/dict2file and faster instrumentation.

a mini cmplog could be done natively by adding `sanitizer-coverage-trace-compares`  (and perhaps trace-div, trace-gep, trace-loads, trace-stores, but unsure about the impact on effectiveness positively or negatively) here:
https://github.com/rust-fuzz/afl.rs/blob/ab62d59ba41c2f101c53e211746f7412ee652745/src/bin/cargo-afl.rs#L365
and then handing `afl-fuzz` the additional parameters with`-c 0` when starting as `cargo afl fuzz  ...`

A better but more complex approach would be to use the rust llvm framework to compile the afl++ llvm plugins and load these.
that would result in full cmplog, faster instrumentation, auto dictionary/dict2file, switch case splitting etc.

**Comment by smoelius** [comment]
> (and perhaps trace-div, trace-gep, trace-loads, trace-stores, ...)

Does it make sense to enable this options if only using mini (not-full) cmplog? Is there an advantage?

**Comment by smoelius** [comment]
#324 includes this line:
```
         -C llvm-args=-sanitizer-coverage-trace-divs \
```
Is that line needed for minicmplog?

**Comment by vanhauser-thc** [comment]
It makes it a bit better

**Comment by louismerlin** [comment]
I'm also working on full compilation of the plugins, it should be ready in the coming days.

**Comment by smoelius** [comment]
> I'm also working on full compilation of the plugins, it should be ready in the coming days.

Does that affect #324?

**Comment by louismerlin** [comment]
Yes #324 might not be necessary if full compilation works. But there is a chance that it is not possible or too complex to finish, so I’d keep the PR open until we know.

**Comment by louismerlin** [comment]
I tried implementing full CmpLog with @brunoproduit, but so far we have been unsuccessful.

@smoelius I think you can already merge mini CmpLog from #324.

We will also publish a draft PR showing where we are stuck next week.

**Comment by brunoproduit** [comment]
Talking with @vanhauser-thc, it seems rustc is [not compiled with llvm plugins activated](https://rust-lang.zulipchat.com/#narrow/stream/187780-t-compiler.2Fwg-llvm/topic/.E2.9C.94.20Running.20Custom.20LLVM.20Pass/near/320275483), meaning we cannot use the cmplog llvm plugins to be used here. Hence https://github.com/rust-fuzz/afl.rs/pull/324 is a good compromise
