### ISSUE TITLE
Proposal to split afl.rs into two packages

### ISSUE THREAD

**Issue by smoelius** [rust-fuzz/afl.rs#335]
I propose that afl.rs be split into two package, `cargo-afl` and `afl`.

Moreover:
- Users install `cargo-afl` via `cargo install cargo-afl`, instead of `cargo install afl` like now.
- A compile error is generated when a user runs `cargo install afl` (similar to what [`cargo install rg`](https://github.com/BurntSushi/rg-cratesio-typosquat) does).
- A warning is generated when a user runs `cargo build` instead of `cargo afl build` on a crate that depends on `afl`.

The last bullet would be accomplished by a build script. Note that there is no easy way to accomplish this with the current one-package setup, because there is no easy way to tell why a build script is run (see https://github.com/rust-lang/cargo/issues/4001).

Pros for these changes:

- The aforementioned warning will help avoid confusion (e.g., #179).
- Building targets that rely on `afl` should be faster, because:
  - The current build script (which is intended for `cargo-afl`) will not need to be run.
  - `cargo-afl`'s dependencies (e.g. clap) will not need to be built.

Cons:

- Maintaining a multi-package project is more difficult.
- User accustomed to running `cargo install afl` will have to adjust.
- CI that runs `cargo install afl` will break. (It may be possible to have a transition period where we generate a warning.)

Does anyone have strong opinions on this? If so, could you please voice them?

**Comment by louismerlin** [comment]
That sounds like a great idea!

Another way to achieve **cargo-afl's dependencies (e.g. clap) will not need to be built.** is through features, like we do [here](https://github.com/srlabs/ziggy/blob/f5551510a1d7b5648822cc97645ef37aceb8c40a/Cargo.toml#L32).

The only difference in workflow this would create is that the `afl` package would have to be imported like this:
```
afl = { version = "*", default-features = false }
```

**Comment by smoelius** [comment]
> Another way to achieve **cargo-afl's dependencies (e.g. clap) will not need to be built.** is through features, like we do [here](https://github.com/srlabs/ziggy/blob/f5551510a1d7b5648822cc97645ef37aceb8c40a/Cargo.toml#L32).

That's a very good point, @louismerlin. Thank you for raising it.

**Comment by smoelius** [comment]
I've received two positive responses (one here and one offline) and no negative responses.

So in about a week, I'm going to implement a transitional message to let users know this change is coming.

**Comment by smoelius** [comment]
Completed by #375
