### ISSUE TITLE
Update 'requirements' section of README to mention compatible LLVM versions

### ISSUE THREAD

**Issue by frewsxcv** [rust-fuzz/afl.rs#41]
one only needs to use LLVM 3.8 (as far as I know) to get AFL to work with Rust programs. we can then stop requiring users to compile Rust to use afl.rs.

**Comment by alexcrichton** [comment]
Note that one part here which may make this difficult is that we tend to upgrade LLVM at unpredictable times. For example right now we'd like to update to LLVM's current tip, and in general we don't provide a guarantee about what LLVM we're linking to.

I agree though that this is an  unfortunate situation :(

**Comment by aidanhs** [comment]
I too am interesting in using an LLVM pass with rust that would be compatible with multiple rust versions. Is there an issue on rust-lang/rust (or rfcs) about this?

**Comment by frewsxcv** [comment]
llvm compatibility is no longer a thing with afl.rs 0.2

https://twitter.com/frewsxcv/status/932799107487461377

https://users.rust-lang.org/t/announcing-afl-rs-0-2-bindings-for-american-fuzzy-lop/13981
