### ISSUE TITLE
Reproducing crashes workflow

### ISSUE THREAD

**Issue by jberryman** [rust-fuzz/afl.rs#463]
This is more of a question or feature request,  but I'm confused about an effective workflow for testing fixes to crashes found during fuzzing.  as documented in the book I can do:
```
cargo afl run --release < fuzz_outputs/main/crashes/…
```

And observe a crash. However if I fix the bug this just hangs it seems. If I run the harness binary directly I see:

``` 
target/release/parser-fuzz-target <  /tmp/asdlklkjasdf
[1]  + 2729446 suspended (signal)  target/release/parser-fuzz-target < /tmp/asdlklkjasdf
```

My goal is to check that all the crashes are fixed;  is there a way to script that without creating a new binary and compiling without instrumentation?

**Comment by smoelius** [comment]
> My goal is to check that all the crashes are fixed; is there a way to script that without creating a new binary and compiling without instrumentation?

You're using the `fuzz!` macro, correct?

The only thing I can think of is to add a `std::process::exit(0);` as the last statement in the `fuzz!` closure body. But I suspect this will impact persistent fuzzing. So you may want to conditionally enable it.

I am sorry I don't have a better answer for you.

**Comment by jberryman** [comment]
> You're using the fuzz! macro, correct?

yes. No worries and thanks for the feedback
