### ISSUE TITLE
Instructions about building from source

### ISSUE THREAD

**Issue by llooFlashooll** [rust-fuzz/afl.rs#504]
Hi authors,

I want to modify a bit to practice and build the project from source. My command is to go to the cargo-afl directory and then `cargo install --path . --force`. This should be the same with `cargo install cargo-afl`.

However, I found differences like I cannot run `cargo afl config --build --force` when I build from source.
The error message is:
```
RUST_BACKTRACE=1 cargo afl config --build --force thread 'main' panicked at cargo-afl/src/main.rs:145:34: called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: Error { kind: NotFound, message: "No such file or directory (os error 2)" } }
```
While I succeeded when installing it from crates.io.

Can you explain the reason for this? Or is there any instruction about building from source? Thank you!

**Comment by smoelius** [comment]
> The error message is: ...

That is not a very helpful error message!

I agree we should have build instructions, but I would like to get to the root cause of the problem you are experiencing now.

I have created a branch `use-anyhow` that should provide more helpful error messages. Could I trouble you to repeat you experiment using that branch?
```
git clone https://github.com/rust-fuzz/afl.rs
cd afl.rs
git checkout use-anyhow
```
If you get an error again, please provide the backtrace.

As a shot in the dark, did you run `git submodule update --init` before running `cargo install ...`?

**Comment by smoelius** [comment]
Sorry, but I am still having trouble determining the source of the error. Specifically, I cannot tell what this line in the backtrace refers to:
```
0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
```
When you install from source, could you add the `--debug` flag? That should add more details to the backtrace.

**Comment by smoelius** [comment]
So this is where the failure occurs: https://github.com/rust-fuzz/afl.rs/blob/6c6b6b0fa1c9d34ff2ace55a49ddc94ba1c1eee4/cargo-afl/src/config.rs#L64-L71

In your  checkout of `afl.rs`, what do you see if you run this?
```sh
ls cargo-afl/AFLplusplus
```

Alternatively, is there anything weird about how your `/tmp` is set up?

**Comment by smoelius** [comment]
> I have run `git submodule update --init --recursive` to sync all the contents in AFLPlusPlus. I git checkout `use-anyhow`.

Could you please try without the `--recursive` flag?

I think some of AFL++'s submodules may contain broken links, and that is what is causing the failure.

**Comment by smoelius** [comment]
Let's please keep this issue open until I have had a chance to write build instructions.

Users should not have to figure out that `--recursive` causes problems (and the code should probably handle that anyway).

Thanks very much for your inquiry! You've revealed some ways in which the code could be improved!

**Comment by smoelius** [comment]
Done. https://github.com/rust-fuzz/book/pull/44
