### ISSUE TITLE
cargo afl build fails while cargo build succeeds.

### ISSUE THREAD

**Issue by GeorgeAndrou** [rust-fuzz/afl.rs#531]
I'm trying to fuzz an old crate pnet_packet-0.26.0 (https://github.com/libpnet/libpnet/tree/v0.26.0) with AFL++.

It seems the issue occurs when using AFL++ to compile a fuzz target that depends on pnet_packet-0.26.0. I'm using rustc 1.81.0-nightly, so I disabled debug assertions for slice::get_unchecked using RUSTFLAGS="-Zub-checks=no" to successfully build pnet_packet with cargo build.

However, when compiling with cargo afl build, the build fails with the following error:

<img width="791" alt="image" src="https://github.com/user-attachments/assets/a9fc1f2c-7364-45c1-bd6c-b5508fdde780">

On the other hand, a normal program with standalone main() and not main (fuzz!({...})) that is calling pnet_packet::icmpv6::ndp::MutableNeighborSolicitPacket::new() compiles fine with cargo build.

The pnet_packet crate uses an older version of the syntex crate, has a custom build.rs script involving OUT_DIR and custom macros. Could any of these interfere with how afl.rs works?

**Comment by smoelius** [comment]
Hi, @GeorgeAndrou. I can reproduce the failure, but I don't understand the code well enough to attribute a cause.

What exactly should this line do? https://github.com/libpnet/libpnet/blob/5498ff4ba5c03bcf7a09a236d62c31a37f2e07a6/pnet_packet/build.rs#L28

**Comment by GeorgeAndrou** [comment]
I'm also not an expert with pnet_packet and syntex, but after some searching, I found the documentation for syntex-0.42.2 that describes the expand() function (https://docs.rs/syntex/0.42.2/src/syntex/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex-0.42.2/src/lib.rs.html#150).

It looks like this function performs macro expansion on a Rust source file and writes the expanded code to an output file.

**Comment by smoelius** [comment]
I am willing to accept this could be a fault of afl.rs. But I cannot immediately think of what it could be doing to cause this.

As a workaround, could you build the `out` directory without `afl`, and then refer to it directly? For me, this looks something like this:
```
RUSTFLAGS="-Zub-checks=no" cargo +nightly build
mv target/debug/build/pnet_packet-a48921551fe85a20/out src
```
Then, change `src/icmpv6.rs` to look like this:
```rust
// include!(concat!(env!("OUT_DIR"), "/icmpv6.rs"));
include!("out/icmpv6.rs");
```

**Comment by GeorgeAndrou** [comment]
The workaround works for me.

Thank you so much!
