### ISSUE TITLE
Error when instrumenting the program

### ISSUE THREAD

**Issue by llooFlashooll** [rust-fuzz/afl.rs#562]
Hi folks, the general instrumentation workflow would be a) modify the AFLPlusPlus project; b) `cargo install --force --path .`; c) `cargo afl build`.

However, when I generate a fuzzer driver such as the one in the tutorial to test `rust-url`. The `afl-llvm-pass.so` only outputs the `main` function name in the fuzzer driver. The other inter-procedural functions in rust-url, std, etc. are not instrumented.

Why does this situation happen? Theoretically, all the functions should be instrumented to track the coverage.

Do you know how to instrument all the dependent functions? I guess there should exist some flags for the compiler? Or any other operations?

Thank you!

**Comment by smoelius** [comment]
I'm not certain I understand the question, but I think you may need to build afl.rs with plugins.

Please try this:
```
cargo +nightly afl config --build --plugins
```
Then, in your target's directory:
```
AFL_DEBUG=1 cargo +nightly afl build
```
When I do this, I see lots of "instrumenting ..." messages (though I haven't yet figured out how to trigger the exact line you cited).

**Comment by smoelius** [comment]
Glad to hear it worked!
