### ISSUE TITLE
Compile failure

### ISSUE THREAD

**Issue by SeanRBurton** [rust-fuzz/afl.rs#57]
When I try to compile the 'regex-afl' crate in https://github.com/SeanRBurton/regex/tree/afl, I get the following error:

`
/home/usr/documents/regex/src/lib.rs:453:42: 453:52 error: /home/usr/documents/regex/regex-afl/target/debug/deps/libafl_plugin-86c859d7ecd403fc.so: undefined symbol: _ZNK4llvm10ModulePass17createPrinterPassERNS_11raw_ostreamERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
/home/sean/usr/documents/regex/src/lib.rs:453 #![cfg_attr(feature = "afl-fuzz", plugin(afl_plugin))]
`

Can you please help me debug this?

**Comment by frewsxcv** [comment]
Which OS/distro are you using? As per the README, you need to install the same version LLVM that rust uses for afl.rs to work. I'm in the process of rewriting the documentation, but basically, you just need to install LLVM 3.8 (if you're using Ubuntu: [llvm-toolchain-3.8](http://packages.ubuntu.com/source/xenial/llvm-toolchain-3.8)). Then you need to point the `LLVM_CONFIG` environment variable at the new `llvm-config` (usually, `export LLVM_CONFIG=$(which llvm-config-3.8)` should suffice). Let me know if this doesn't work.

**Comment by frewsxcv** [comment]
@SeanRBurton Have any luck?

**Comment by frewsxcv** [comment]
Let me know if you're still having issues and I can reopen this

**Comment by keeperofdakeys** [comment]
So I've actually come across this same issue (missing this specific symbol) on two different distros. On a reasonably up-to-date Gentoo installation, and a Fedora 24 installation. Both have llvm 3.8 installed, and are using the specific nightly compiler that the book specifies.

Did you have any tips on working out what is causing this?

**Comment by frewsxcv** [comment]
@keeperofdakeys Which version of Rust? `rustc --version`

**Comment by keeperofdakeys** [comment]
```
user@host# rustc --version
rustc 1.12.0-nightly (f164cf5d6 2016-07-29)
```

And according to grep, the symbol exists in libLLVM-38.so.
```
user@host# grep _ZNK4llvm10ModulePass17createPrinterPassERNS_11raw_ostreamERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE /usr/lib/ -r
Binary file /usr/lib/libLLVM-3.8.so matches
```

The error I get is the same, pointing to libafl_plugin-.*.so.

**Comment by frewsxcv** [comment]
What does `llvm-config-3.8 --cxxflags` return? If that fails, `llvm-config --cxxflags`

**Comment by keeperofdakeys** [comment]
user@host# llvm-config --cxxflags
llvm-config --cxxflags
-I/usr/include -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic  -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -std=c++11 -ffunction-sections -fdata-sections -O2 -g -DNDEBUG  -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS

**Comment by frewsxcv** [comment]
How about `which llvm-config` and `llvm-config --version`?

**Comment by keeperofdakeys** [comment]
```
user@host# which llvm-config
/usr/bin/llvm-config
user@host# llvm-config --version
3.8.0
```

The /usr/bin/llvm-config file is a softlink that is controlled using the fedora "alternatives" command, which in this case only has one option of llvm 3.8 x86_64.

**Comment by frewsxcv** [comment]
@keeperofdakeys I'm going to try to reproduce issue via a `Dockerfile`

```dockerfile
FROM fedora:23

RUN dnf install -y file tar

RUN curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly --disable-sudo

WORKDIR /opt/afl.rs

ADD . .
````

How did you install LLVM 3.8? I don't see it in the package repository. I'm not too familiar with Fedora, so forgive me if I'm missing something.

**Comment by keeperofdakeys** [comment]
They should be called llvm and llvm-devel. Also you'll want to use fedora 24, to match my configuration (it's also the current stable).
```
user@host# dnf list installed | grep llvm
llvm.x86_64                            3.8.0-1.fc24                @@commandline
llvm-devel.x86_64                      3.8.0-1.fc24                @fedora      
llvm-libs.i686                         3.8.0-1.fc24                @@commandline
llvm-libs.x86_64                       3.8.0-1.fc24                @@commandline
```

**Comment by keeperofdakeys** [comment]
I'd say the symbol belongs to this in libLLVM (extracted using objdump).

00564490 g    DF .text	00000032  Base        llvm::ModulePass::createPrinterPass(llvm::raw_ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const

**Comment by vks** [comment]
I'm also having this issue on Ubuntu with a locally installed LLVM.

**Comment by keeperofdakeys** [comment]
@frewsxcv Have you had any luck with this?

**Comment by frewsxcv** [comment]
Haven't really looked into this yet. Was going to set aside some time today or this weekend for this. Sorry for the delay.

**Comment by frewsxcv** [comment]
Just wrote this Fedora-based Dockerfile:

```dockerfile
FROM fedora:24

RUN dnf install -y file tar llvm llvm-devel gcc-c++

RUN curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly --disable-sudo

WORKDIR /opt/afl.rs

ADD . .
```

and ran these commands:

```
docker build -f ci/Dockerfile.fedora -t afl.rs-fedora .
docker run -it afl.rs-fedora cargo test
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading libc v0.2.15
 Downloading tempdir v0.3.5
 Downloading byteorder v0.3.13
 Downloading gcc v0.3.33
 Downloading quale v1.0.0
 Downloading rand v0.3.14
   Compiling libc v0.2.15
   Compiling byteorder v0.3.13
   Compiling gcc v0.3.33
   Compiling rand v0.3.14
   Compiling quale v1.0.0
   Compiling afl-plugin v0.1.4 (file:///opt/afl.rs/afl-plugin)
   Compiling afl v0.1.4 (file:///opt/afl.rs)
   Compiling afl-sys v0.1.4 (file:///opt/afl.rs/afl-sys)
   Compiling tempdir v0.3.5
error: /opt/afl.rs/target/debug/deps/libafl_plugin.so: undefined symbol: _ZNK4llvm10ModulePass17createPrinterPassERNS_11raw_ostreamERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
 --> examples/integer-overflow.rs:9:11
  |
9 | #![plugin(afl_plugin)]
  |           ^^^^^^^^^^

Build failed, waiting for other jobs to finish...
error: /opt/afl.rs/target/debug/deps/libafl_plugin.so: undefined symbol: _ZNK4llvm10ModulePass17createPrinterPassERNS_11raw_ostreamERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
 --> examples/hello.rs:9:11
  |
9 | #![plugin(afl_plugin)]
  |           ^^^^^^^^^^

Build failed, waiting for other jobs to finish...
error: Could not compile `afl`.

To learn more, run the command again with --verbose.
```

So, I can reproduce the issue now :)

**Comment by frewsxcv** [comment]
I can reproduce this issue on the Ubuntu-based Dockerfile with these changes:

```diff
diff --git a/ci/Dockerfile b/ci/Dockerfile
index cd9cc78..570344a 100644
--- a/ci/Dockerfile
+++ b/ci/Dockerfile
@@ -5,8 +5,10 @@ RUN apt-get update && apt-get install -y \
   file \
   g++ \
   g++-multilib \
-  g++-4.9 \
-  g++-4.9-multilib \
+  g++-5 \
+  g++-5-multilib \
+  # g++-4.9 \
+  # g++-4.9-multilib \
   libstdc++-4.8-dev \
   llvm-3.8
 
@@ -16,4 +18,4 @@ WORKDIR /opt/afl.rs
 
 ADD . .
 
-ENV CXX /usr/bin/g++-4.9
+ENV CXX /usr/bin/g++-5
```

So maybe this only happens with g++ versions greater than 4.9?

**Comment by frewsxcv** [comment]
@vks @keeperofdakeys Can you both let me know which version of g++ you're using? `g++ --version`

**Comment by keeperofdakeys** [comment]
5.4.0 on Gentoo, 6.2.1 on fedora

**Comment by keeperofdakeys** [comment]
I tried using gcc 4.9.4 on Gentoo, and the symbol missing changed to ```_ZNK4llvm10ModulePass17createPrinterPassERNS_11raw_ostreamERKSs```.

**Comment by frewsxcv** [comment]
> I tried using gcc 4.9.4 on Gentoo, and the symbol missing changed to _ZNK4llvm10ModulePass17createPrinterPassERNS_11raw_ostreamERKSs.

Did you do a `cargo clean` before trying to build again?

**Comment by keeperofdakeys** [comment]
Yep, though rust and llvm were built with gcc 5.4.0.

**Comment by kevincox** [comment]
@frewsxcv I recall that GCC (and I think LLVM) recently switched it's name mangling. However if I am recompiling both I don't know why that would be a problem.

**Comment by frewsxcv** [comment]
Over the past few weeks, I've learned what a pain ABI compatibility is. As seen in this discussion, relying on trying to match library/compilers versions with pre-built Rust binaries appears to be unsustainable. Unless someone has a better idea here, I'm probably just going to have to recommend one use Docker, which will have a base image that will have ABI compatibility. I'm in the process of updating the docs to reflect this. Will add a comment here when a PR is open. Hopefully sometime today.

**Comment by kevincox** [comment]
May I ask why you need compatibility? If rust and my program are compiled on the same machine shouldn't it be fine?

That being said as much as I am usually OK with docker this would be a fairly good use case and I would give it a run.

**Comment by frewsxcv** [comment]
If you are compiling rustc and your project on your machine, then you should be good to go (as opposed to downloading a pre-built rustc binary via rustup). No ABI incompatibility issues will occur in that scenario.

I could recommend in the documentation all users of afl.rs also compile rustc, but I'm assuming that using a Docker image is easier and faster to use. In retrospect, maybe I'll explicitly message both of these options, but recommend the Docker approach.

**Comment by kevincox** [comment]
Also IIRC LLVM has weak to no binary compatibility guarantees so no matter how hard you try it will always be a pain.

**Comment by frewsxcv** [comment]
You'll need to reference the `llvm-config` binary (which is produced in the `target/` folder of rust-lang/rust) via the `LLVM_CONFIG` environment variable for it to work:

**Comment by frewsxcv** [comment]
Sorry for the delay here, some personal things got in the way from me working on this. I updated the documentation in #102 to use a Docker approach for using afl.rs. It's not an ideal flow (not even close), but it will hopefully prevent anyone from having compilation issues. You can check out the tutorial here:

https://frewsxcv.github.io/afl.rs/setup.html

If anyone has suggestions for improvement, please let me know! I'll leave this Issue open for the time being and will close it in a week or so if I haven't heard anything.

**Comment by infinity0** [comment]
Could the non-Docker instructions please be restored? We dynamically link Rust against LLVM in Debian so there should be no ABI issues there. This is easy once you figure out how to do it, but other distros probably haven't done this yet.

**Comment by frewsxcv** [comment]
For people who are interested in fuzzing Rust projects, I'd now recommend looking at [cargo-fuzz](https://github.com/rust-fuzz/cargo-fuzz) for now.

**Comment by frewsxcv** [comment]
hi everyone 👋 

it's been a while since we last spoke. a lot has changed in the world

in any case, i rewrote afl.rs the past couple weeks. for more info, see this URLO post: https://users.rust-lang.org/t/announcing-afl-rs-0-2-bindings-for-american-fuzzy-lop/13981

i think the new version won't have this compile fail issue anymore, so i'm going to close this. if you come across any issues with the new version, feel free to open a new issue

**Comment by DataCorrupted** [comment]
I recently run into the same problem and ended up in this thread since we are missing the same symbol :)
Unfortunately, it didn't provide me with an answer, so I am going to write a short answer here in case anyone else stumbled here again.

`_ZNK4llvm10ModulePass17createPrinterPassERNS_11raw_ostreamERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE` is a symbol in `Pass.cpp`. Using cxx11 ABI this is what you get. Yet on LLVM runtime, the same symbol is (at least until LLVM 8) compiled using cxx03 ABI, thus the mismatch.

To prevent this from happening, make sure that when compiling **your custom pass**, add ` -D_GLIBCXX_USE_CXX11_ABI=0  -fno-rtti` to it and you should be good.
